name: giphy_dev
description: Buscador de Gif

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  share: ^0.6.1+1
  transparent_image: ^1.0.0
  http: ^0.12.0+2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

